vim.pack.add({
  { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects" },
})

vim.filetype.add({
  extension = {
    gotmpl = "gotmpl",
  },
  pattern = {
    [".*/templates/.*%.tpl"] = "helm",
    [".*/templates/.*%.ya?ml"] = "helm",
    ["helmfile.*%.ya?ml"] = "helm",
  },
})
require("nvim-treesitter.configs").setup({
  highlight = { enable = true },
  indent = { enable = true },
  ensure_installed = {
    "asm",
    "bash",
    "c",
    "cmake",
    "c_sharp",
    "css",
    "cpp",
    "dart",
    "diff",
    "dockerfile",
    "go",
    "gomod",
    "gowork",
    "gosum",
    "graphql",
    "gitignore",
    "git_config",
    "helm",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "json5",
    "ini",
    "kconfig",
    "kotlin",
    "latex",
    "lua",
    "luadoc",
    "luap",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "ninja",
    "norg",
    "objc",
    "php",
    "proto",
    "printf",
    "python",
    "query",
    "regex",
    "rust",
    "ron",
    "rst",
    "scss",
    "solidity",
    "sql",
    "ssh_config",
    "svelte",
    "swift",
    "toml",
    "tsx",
    "typescript",
    "typst",
    "vue",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
    "zig",
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<C-space>",
      node_incremental = "<C-space>",
      scope_incremental = false,
      node_decremental = "<bs>",
    },
  },
  textobjects = {
    move = {
      enable = true,
      goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer", ["]a"] = "@parameter.inner" },
      goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer", ["]A"] = "@parameter.inner" },
      goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer", ["[a"] = "@parameter.inner" },
      goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer", ["[A"] = "@parameter.inner" },
    },
  },
})
