vim.filetype.add({
  extension = {
    gotmpl = "gotmpl",
  },
  pattern = {
    [".*/templates/.*%.tpl"] = "helm",
    [".*/templates/.*%.ya?ml"] = "helm",
    ["helmfile.*%.ya?ml"] = "helm",
  },
})
require("tree-sitter-manager").setup({
  ensure_installed = {
    "asm",
    "bash",
    "c",
    "cmake",
    "c_sharp",
    "css",
    "cpp",
    "dart",
    "diff",
    "dockerfile",
    "elixir",
    "erlang",
    "go",
    "gomod",
    "gowork",
    "gosum",
    "graphql",
    "gitignore",
    "git_config",
    "helm",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "ini",
    "kconfig",
    "kotlin",
    "latex",
    "lua",
    "luadoc",
    "luap",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "ninja",
    "objc",
    "php",
    "proto",
    "printf",
    "python",
    "query",
    "racket",
    "regex",
    "rust",
    "ron",
    "rst",
    "scss",
    "solidity",
    "sql",
    "ssh_config",
    "svelte",
    "swift",
    "toml",
    "tsx",
    "typescript",
    "typst",
    "vue",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
    "zig",
  },
  auto_install = true,
  highlight = false,
})
